import os
import sys

import numpy as np

sys.setrecursionlimit(2500)

import sisyphus.toolkit as tk
from arxiv.huggingface.search import HuggingfaceSearchJob, NeuralMBRJob, DecisionLayerJob, CalibrateThresholdJob, MathdialQualityJob, MathDialMBRJob, MathDialEvalJob, \
 DialogActCalibrationJob, ConformalMathDialMBRJob, MathDialMinMaxJob

Path = tk.Path

code_root = "/path/to/code/"

DIALOG_ACT_PROMPT = """
You are given a conversation between a student and a teacher, where the teacher attempts to guide the student towards correcting their incorrect solution attempt.
Your task is to indicate the tutoring strategy that the teacher should use in their next utterance from the following choices.
DO NOT CLASSIFY THE CURRENT TEACHER UTTERANCE.
Follow the guidelines below, where there is an explanation of intents behind each strategy with examples.

0. Focus:
    - Seek Strategy: So what should you do next?
    - Guiding Student: Can you calculate . . . ?
    - Recall Relevant Information: Can you reread the question and tell me what is . . . ?

1. Probing:
    - Asking for Explanation: Why do you think you need to add these numbers?
    - Seeking Self Correction: Are you sure you need to add here?
    - Perturbing the Question: How would things change if they had . . . items instead?
    - Seeking World Knowledge: How do you calculate the perimeter of a square?

2. Telling:
    - Revealing Strategy: You need to add . . . to . . . to get your answer.
    - Revealing Answer No, he had . . . items.

3. Generic:
    - Greeting/Farewell: Hi . . . , how are you doing with the word problem?
    - General inquiry: Can you go walk me through your solution?

Telling should only be used rarely, for example, if the student is stuck.

## Output Format
Return only one numer in the range 0-3 to indicate the tutoring strategy from the list and nothing else.
"""

QUALITY_PROMPT_NEW = """
You are given a conversation between a student and a teacher, where the teacher attempts to guide the student towards correcting their incorrect solution attempt, a guideline for tutoring strategies and a guideline for scoring.
Your task is to predict the quality of the last reponse generated by the teacher model.

# Tutoring Strategies

0. focus:
    - Seek Strategy: So what should you do next?
    - Guiding Student: Can you calculate . . . ?
    - Recall Relevant Information: Can you reread the question and tell me what is . . . ?

1. probing:
    - Asking for Explanation: Why do you think you need to add these numbers?
    - Seeking Self Correction: Are you sure you need to add here?
    - Perturbing the Question: How would things change if they had . . . items instead?
    - Seeking World Knowledge: How do you calculate the perimeter of a square?

2. telling:
    - Revealing Strategy: You need to add . . . to . . . to get your answer.
    - Revealing Answer No, he had . . . items.

3. generic:
    - Greeting/Farewell: Hi . . . , how are you doing with the word problem?
    - General inquiry: Can you go walk me through your solution?

# Scoring Guidelines

Use these criteria to score a response according to the following rubrics:
(a) correctness: the teacher should guide the student towards the correct answer and not state incorrect facts
(b) scaffolding: the teacher should help the student to cognitively engage with the problem without telling the final solution. The teacher can provide intermediate steps as a scaffold. If the student has reached the solution the teacher should indicate this.

0: The response is either inappropriate, does not fit to the given tutoring strategy or does not satisfy any of the above criteria.

1: The response does not provide the student with any actionable feedback or room to improve their understanding. The response tells the student the final solution too early.

2: The response has good pedagogical quality and provides the student with some room to improve their understanding. It satisfies most of the criteria but not all of them. It fits the tutoring strategy.

3: The response is of high pedagogical quality. It provides the student with explicit ways to improve their understanding. It satisfies all of the above criteria. The response is tailored to the tutoring strategy. It does not provide the final solution unless the student has reached it themselves or is clearly stuck.

## Output Format
Return only one numer in the range 0-3 to indicate the quality of the teacher response according to the Scoring Guidelines and nothing else.
"""


QUALITY_PROMPT = """
You are given a conversation between a student and a teacher, where the teacher attempts to guide the student towards correcting their incorrect solution attempt, a guideline for tutoring strategies and a guideline for scoring.
Your task is to predict the quality of the last reponse generated by the teacher model.
Follow the scores under Scoring Guidelines as closely as possible.
In order to find out if a response fits a tutoring strategy, you can compare it to the examples in the tutoring strategy guidelines.

# Tutoring Strategies

0. focus:
    - Seek Strategy: So what should you do next?
    - Guiding Student: Can you calculate . . . ?
    - Recall Relevant Information: Can you reread the question and tell me what is . . . ?

1. probing:
    - Asking for Explanation: Why do you think you need to add these numbers?
    - Seeking Self Correction: Are you sure you need to add here?
    - Perturbing the Question: How would things change if they had . . . items instead?
    - Seeking World Knowledge: How do you calculate the perimeter of a square?

2. telling:
    - Revealing Strategy: You need to add . . . to . . . to get your answer.
    - Revealing Answer No, he had . . . items.

3. generic:
    - Greeting/Farewell: Hi . . . , how are you doing with the word problem?
    - General inquiry: Can you go walk me through your solution?

# Scoring Guidelines

0: The response is either inappropriate, does not fit to the given tutoring strategy at all, or tells the solution early on in the conversation without any need for it.

1: The response does not fit the tutoring strategy well, tells the solution too early, or does not provide the student with any actionable feedback or room to improve their understanding.

2: The response somewhat fits the tutoring strategy. It has good pedagogical quality and provides the student with some room to improve their understanding.

3: The response fits the tutoring strategy. The response is of high pedagogical quality. It does not tell the solution directly unless absolutely necessary. It provides the student with explicit ways to improve their understanding.

## Output Format
Return only one numer in the range 0-3 to indicate the quality of the teacher response according to the Scoring Guidelines and nothing else.
"""

QUALITY_PROMPT_2 = """
You are given a conversation between a student and a teacher, where the teacher attempts to guide the student towards correcting their incorrect solution attempt, a guideline for tutoring strategies and a guideline for scoring.
Your task is to predict the quality of the last reponse generated by the teacher model.

# Tutoring Strategies

0. focus:
    - Seek Strategy: So what should you do next?
    - Guiding Student: Can you calculate . . . ?
    - Recall Relevant Information: Can you reread the question and tell me what is . . . ?

1. probing:
    - Asking for Explanation: Why do you think you need to add these numbers?
    - Seeking Self Correction: Are you sure you need to add here?
    - Perturbing the Question: How would things change if they had . . . items instead?
    - Seeking World Knowledge: How do you calculate the perimeter of a square?

2. telling:
    - Revealing Strategy: You need to add . . . to . . . to get your answer.
    - Revealing Answer No, he had . . . items.

3. generic:
    - Greeting/Farewell: Hi . . . , how are you doing with the word problem?
    - General inquiry: Can you go walk me through your solution?

# Scoring Guidelines

Use these criteria to score a response according to the following rubrics:
(a) correctness: the teacher should guide the student towards the correct answer and not state incorrect facts
(b) scaffolding instead of giving away the answer: the teacher should help the student to cognitively engage with the problem and discover the answer on their own
(c) encourage self-correction: by correctly identifying the student mistake and first giving the student the opportunity to self-correct and learn from a mistake 
(d) not overloading the student: manage cognitive load by not giving too much information at once.

0: The response is either inappropriate, does not fit to the given tutoring strategy or does not satisfy any of the above criteria.

1: The response tells the solution too early, or does not provide the student with any actionable feedback or room to improve their understanding. Overall, it only satisfies few of the criteria.

2: The response has good pedagogical quality and provides the student with some room to improve their understanding. It satisfies most of the criteria but not all of them. It fits the tutoring strategy.

3: The response is of high pedagogical quality. It does not tell the solution directly unless absolutely necessary. It provides the student with explicit ways to improve their understanding. It satisfies all of the above criteria. The response is tailored to the tutoring strategy.

## Output Format
Return only one numer in the range 0-3 to indicate the quality of the teacher response according to the Scoring Guidelines and nothing else.
"""



QUALITY_PROMPT_5likert = """
You are given a conversation between a student and a teacher, where the teacher attempts to guide the student towards correcting their incorrect solution attempt, a guideline for tutoring strategies and a guideline for scoring.
Your task is to predict the quality of the last reponse generated by the teacher model.

# Tutoring Strategies

0. focus:
    - Seek Strategy: So what should you do next?
    - Guiding Student: Can you calculate . . . ?
    - Recall Relevant Information: Can you reread the question and tell me what is . . . ?

1. probing:
    - Asking for Explanation: Why do you think you need to add these numbers?
    - Seeking Self Correction: Are you sure you need to add here?
    - Perturbing the Question: How would things change if they had . . . items instead?
    - Seeking World Knowledge: How do you calculate the perimeter of a square?

2. telling:
    - Revealing Strategy: You need to add . . . to . . . to get your answer.
    - Revealing Answer No, he had . . . items.

3. generic:
    - Greeting/Farewell: Hi . . . , how are you doing with the word problem?
    - General inquiry: Can you go walk me through your solution?

# Scoring Guidelines

Use these criteria to score a response according to the following rubrics:
(a) correctness: the teacher should guide the student towards the correct answer and not state incorrect facts
(b) scaffolding instead of giving away the answer: the teacher should help the student to cognitively engage with the problem and discover the answer on their own
(c) encourage self-correction: by correctly identifying the student mistake and first giving the student the opportunity to self-correct and learn from a mistake 
(d) not overloading the student: manage cognitive load by not giving too much information at once.

0: The response is either inappropriate, does not fit to the given tutoring strategy or does not satisfy any of the above criteria.

1: The response tells the solution too early, or does not provide the student with any actionable feedback or room to improve their understanding. Overall, it only satisfies few of the criteria.

2: The response has good pedagogical quality and provides the student with some room to improve their understanding. It satisfies most of the criteria but not all of them. It fits the tutoring strategy but not perfectly.

3: The response is of high pedagogical quality. It satisfies almost all criteria above and fits the tutoring strategy but is not completely tailored to it. It does not tell the solution directly, unless at the end of the conversation.

4: The response is of exceptional pedagogical quality. It does not tell the solution directly unless absolutely necessary. It provides the student with explicit ways to improve their understanding. It satisfies all of the above criteria. The response is tailored to the tutoring strategy.

## Output Format
Return only one numer in the range 0-4 to indicate the quality of the teacher response according to the Scoring Guidelines and nothing else.
"""

async def main_fn():
    code_root = "/path/to/code/"

    beta1 = 0.9
    beta2 = 0.99999


    for seed in [1]:
        nbest = 32
        model = "eth-nlped/TutorRL-7B" 
        for quality_prompt, desc in zip([QUALITY_PROMPT_5likert], ["5likert"]):

            config = {
                "model_name_or_path": "eth-nlped/TutorRL-7B",
                "per_device_eval_batch_size": 128,
                "gradient_accumulation_steps": 1,
                "max_input_length": 32768,
                "max_output_length": 256,
                "seed": seed,
                "manual_seed": seed,
                "wandb_project": "TODO",
                "method": "mathdial_sample",
                "eval_steps": 1000,
                "bf16": True
            }

            dataset = "mathdial"
            code_root = "/path/to/code/"

            search_data_config = {
                'dataset_name': os.path.join(code_root, f'arxiv/datasets/{dataset}.py'),
                'dataset_config_name': "chat",
                'dataset_test_split': "test",
            }

            config["generation_do_sample"] = True
            config["generation_beam_size"] = nbest # 16 for old run
            config["num_return_sequences"] = nbest
            config["generation_temperature"] = 1.0
            config["generation_max_len"] = 256

            config["tokenizer_name"] = model
            config["per_device_eval_batch_size"] = 8
            sbatch_args = "-w lenny,nelson,penelope,scratchy,remus,rubeus --nodes 1"

            search_job = HuggingfaceSearchJob(
                code_root=code_root,
                model_path=model,
                config=config,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"mathdial_test_full_{model}_32.json", search_job.out_search_file)

            config["generation_max_len"] = 1
            config["tokenizer_name"] = "meta-llama/Llama-3.2-3B-Instruct"
            config["method"] = "dialog_act"
            config["possible_acts"] = "focus;probing;telling;generic"
            config["system_prompt"] = DIALOG_ACT_PROMPT
            config["generation_beam_size"] = 64 # 16 for old run
            config["num_return_sequences"] = 64
            dialog_act_job = HuggingfaceSearchJob(
                code_root=code_root,
                model_path="/path/to/llama3.1-8b-mathdial-acts",
                config=config,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_qwen3_14b_acts.json", dialog_act_job.out_search_file)

            search_data_config["dataset_test_split"] = "train"
            dialog_act_job_calibration = HuggingfaceSearchJob(
                code_root=code_root,
                model_path="/path/to/llama3.1-8b-mathdial-acts",
                config=config,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_llama31_8b_acts_calibration.json", dialog_act_job_calibration.out_search_file)

            calibration_job = DialogActCalibrationJob(
                code_root=code_root,
                model_path="/path/to/llama3.1-8b-mathdial-acts",
                acts_file=dialog_act_job_calibration.out_search_file,
                config=config,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_llama31_8b_acts_calibration_threshold.json", calibration_job.out_search_file)

            search_data_config["dataset_test_split"] = "test"

            config["tokenizer_name"] = "/path/to/qwen3-14b-5-likert/" ####

            config["possible_quality_scores"] = "0;1;2;3;4"

            config["generation_beam_size"] = nbest 
            config["num_return_sequences"] = nbest
            config["generation_max_len"] = 1
            config["tokenizer_name"] = "/path/to/qwen3-14b-mathdial-acts"
            config["method"] = "mathdial_quality"
            config["possible_acts"] = "focus;probing;telling;generic"
            config["possible_scores"] = "0;1;2;3"
            config["system_prompt"] = quality_prompt
            config["per_device_eval_batch_size"] = 1024
            quality_job = MathdialQualityJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-5-likert/",#"/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_quality.json", quality_job.out_search_file)

            mbr_job = MathDialMBRJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_mbr.json", mbr_job.out_search_file)

            conformal_mbr_job = ConformalMathDialMBRJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                conformal_file=calibration_job.out_search_file,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_minmax.json", conformal_mbr_job.out_search_file)

            minmax_job = MathDialMinMaxJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                conformal_file=calibration_job.out_search_file,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=6 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_mbr_conformal.json", minmax_job.out_search_file)


            config["use_for_eval"] = True

            eval_job = MathDialEvalJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                mbr_file=mbr_job.out_search_file,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=7 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_{desc}_{seed}.metrics.json", eval_job.out_search_file)

            eval_job_conformal = MathDialEvalJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                mbr_file=conformal_mbr_job.out_search_file,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=7 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_{desc}_conformal_{seed}.metrics.json", eval_job_conformal.out_search_file)

            eval_job_minmax = MathDialEvalJob(
                code_root=code_root,
                model_path="/path/to/qwen3-14b-mathdial-acts",
                config=config,
                responses_file=search_job.out_search_file,
                acts_file=dialog_act_job.out_search_file,
                quality_file=quality_job.out_search_file,
                search_data_config=search_data_config,
                mbr_file=minmax_job.out_search_file,
                mem_rqmt=64,
                time_rqmt=24,
                sbatch_args=sbatch_args, #
                rerun=7 # 5
            )
            tk.register_output(f"tutoring_llama/mathdial_test_full_{model}_{nbest}_{desc}_minmax_{seed}.metrics.json", eval_job_minmax.out_search_file)

            config["possible_quality_scores"] = "0;1;2;3"

async def async_main():
    await main_fn()

async def py():
    await async_main()
